name: kibla_app
description: Islamic prayer application in Albanian language with qibla direction, prayer times, duas, and mosque finder.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Menaxhimi i gjendjes
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Lokalizimi dhe formatimi
  intl: 0.20.2  # Updated to match flutter_localizations requirement

  # Navigimi
  go_router: ^10.1.2

  # Ruajtja lokale
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Gjeolokalizimi dhe busulla
  geolocator: ^10.1.0
  flutter_compass: ^0.7.0
  geocoding: ^2.1.0

  # Hartat
  google_maps_flutter: ^2.5.0

  # Kalendari islamik
  hijri: ^3.0.0

  # Llogaritja e kohëve të faljes
  adhan: ^2.0.0-nullsafety.2

  # Njoftimet lokale
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2

  # Audio dhe share
  audioplayers: ^5.1.0
  share_plus: ^7.0.2

  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  just_audio: ^0.10.3

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

dependency_overrides:
  flutter_compass: ^0.8.0  # Using a newer version that's compatible with SDK 35
